# Generated by Django 6.0.4 on 2026-06-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock / Cantidad')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para préstamo')),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Almacén / Estante')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo_sku'], name='inventario__codigo__32a2e9_idx'), models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'), models.Index(fields=['stock'], name='inventario__stock_0a3383_idx')],
            },
        ),
    ]
