# Generated by Django 6.0.4 on 2026-08-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estante', models.CharField(max_length=100, verbose_name='Estante')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('responsable', models.CharField(max_length=150, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['id_estante'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_proveedor', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('correo_proveedor', models.EmailField(max_length=254, verbose_name='Correo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nit_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('tipo_de_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo de movimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de movimiento')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventario', verbose_name='Inventario')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.inventario', verbose_name='Inventario')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimientos', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de movimiento',
                'verbose_name_plural': 'Detalles de movimiento',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código / SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock / Cantidad')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para préstamo')),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Almacén / Estante')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria', verbose_name='Categoría')),
                ('estante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='almacenamiento.estante', verbose_name='Estante')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada (Stock)'), ('salida', 'Salida (Baja)'), ('prestamo', 'Préstamo Entregado'), ('devolucion', 'Devolución Recibida'), ('ajuste', 'Ajuste Manual')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('stock_anterior', models.PositiveIntegerField(default=0, verbose_name='Stock anterior')),
                ('stock_nuevo', models.PositiveIntegerField(default=0, verbose_name='Stock nuevo')),
                ('usuario_nombre', models.CharField(blank=True, default='Sistema', max_length=150, verbose_name='Usuario / Responsable')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_movimientos', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento Kardex',
                'verbose_name_plural': 'Movimientos Kardex',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='Edicion_limitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('V', 'Vigente'), ('D', 'Descontinuado')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateTimeField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_sku'], name='inventario__codigo__32a2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='inventario__stock_0a3383_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['id_estante'], name='inventario__id_esta_54b5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientos',
            index=models.Index(fields=['fecha_movimiento'], name='inventario__fecha_m_0e3855_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientos',
            index=models.Index(fields=['tipo_de_movimiento'], name='inventario__tipo_de_305682_idx'),
        ),
    ]
