# Generated by Django 6.0.4 on 2026-08-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("almacenamiento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaHerramienta",
            fields=[
                (
                    "codigo_categoria",
                    models.AutoField(
                        db_column="codigo_categoria", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo_herramienta",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de herramienta",
                    ),
                ),
                (
                    "nombre_categoria",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de categoría"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Categoría de Herramienta",
                "verbose_name_plural": "Categorías de Herramientas",
                "db_table": "categoria_herramienta",
                "ordering": ["nombre_categoria"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "codigo_proveedor",
                    models.AutoField(
                        db_column="codigo_proveedor", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nit_proveedor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="NIT",
                    ),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono de contacto",
                    ),
                ),
                (
                    "correo_proveedor",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Correo del proveedor",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "proveedor",
                "ordering": ["nit_proveedor"],
            },
        ),
        migrations.CreateModel(
            name="Herramienta",
            fields=[
                (
                    "codigo_herramienta",
                    models.AutoField(
                        db_column="codigo_herramienta",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_SKU",
                    models.CharField(
                        blank=True,
                        db_column="codigo_SKU",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Código SKU",
                    ),
                ),
                (
                    "nombre_herramienta",
                    models.CharField(
                        db_column="nombre_herramienta",
                        max_length=100,
                        verbose_name="Nombre de herramienta",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "disponibilidad",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Disponibilidad",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de ingreso"
                    ),
                ),
                (
                    "codigo_categoria",
                    models.ForeignKey(
                        db_column="codigo_categoria",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="herramientas",
                        to="inventario.categoriaherramienta",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Herramienta",
                "verbose_name_plural": "Herramientas",
                "db_table": "herramienta",
                "ordering": ["nombre_herramienta"],
            },
        ),
        migrations.CreateModel(
            name="Suministro",
            fields=[
                (
                    "codigo_suministro",
                    models.AutoField(
                        db_column="codigo_suministro", primary_key=True, serialize=False
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "codigo_herramienta",
                    models.ForeignKey(
                        db_column="codigo_herramienta",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="suministros",
                        to="inventario.herramienta",
                        verbose_name="Herramienta",
                    ),
                ),
                (
                    "codigo_inventario",
                    models.ForeignKey(
                        blank=True,
                        db_column="codigo_inventario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suministros",
                        to="almacenamiento.existencia",
                        verbose_name="Existencia",
                    ),
                ),
                (
                    "codigo_proveedor",
                    models.ForeignKey(
                        db_column="codigo_proveedor",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="suministros",
                        to="inventario.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suministro",
                "verbose_name_plural": "Suministros",
                "db_table": "suministro",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Traslado",
            fields=[
                (
                    "codigo_traslado",
                    models.AutoField(
                        db_column="codigo_traslado", primary_key=True, serialize=False
                    ),
                ),
                ("cantidad_total", models.IntegerField(verbose_name="Cantidad Total")),
                (
                    "tipo_movimiento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "fecha_movimiento",
                    models.DateField(verbose_name="Fecha de movimiento"),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "codigo_inventario",
                    models.ForeignKey(
                        blank=True,
                        db_column="codigo_inventario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traslados",
                        to="almacenamiento.existencia",
                        verbose_name="Existencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traslado",
                "verbose_name_plural": "Traslados",
                "db_table": "traslado",
                "ordering": ["-fecha_movimiento"],
            },
        ),
        migrations.CreateModel(
            name="DetalleTraslado",
            fields=[
                (
                    "codigo_detalle",
                    models.AutoField(
                        db_column="codigo_detalle", primary_key=True, serialize=False
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "codigo_herramienta",
                    models.ForeignKey(
                        db_column="codigo_herramienta",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="detalles_traslado",
                        to="inventario.herramienta",
                        verbose_name="Herramienta",
                    ),
                ),
                (
                    "codigo_traslado",
                    models.ForeignKey(
                        db_column="codigo_traslado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.traslado",
                        verbose_name="Traslado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Traslado",
                "verbose_name_plural": "Detalles de Traslado",
                "db_table": "detalle_traslado",
            },
        ),
    ]
