# Generated by Django 6.0.4 on 2026-06-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estante',
        ),
    ]
