# Generated by Django 6.0.4 on 2026-07-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_proveedor', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('correo_proveedor', models.EmailField(max_length=254, verbose_name='Correo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nit_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estante', models.CharField(max_length=100, verbose_name='Estante')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('responsable', models.CharField(max_length=150, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['id_estante'],
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('tipo_de_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo de movimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de movimiento')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventario', verbose_name='Inventario')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.inventario', verbose_name='Inventario')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimientos', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de movimiento',
                'verbose_name_plural': 'Detalles de movimiento',
            },
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['id_estante'], name='inventario__id_esta_54b5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientos',
            index=models.Index(fields=['fecha_movimiento'], name='inventario__fecha_m_0e3855_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientos',
            index=models.Index(fields=['tipo_de_movimiento'], name='inventario__tipo_de_305682_idx'),
        ),
    ]
