# Generated by Django 6.0.4 on 2026-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='stock_real',
            field=models.IntegerField(db_column='stock', default=1, verbose_name='Stock'),
        ),
    ]
