# Generated by Django 6.0.4 on 2026-08-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "codigo_almacen",
                    models.AutoField(
                        db_column="codigo_almacen", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "dimensiones",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dimensiones",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ubicación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
                "db_table": "almacen",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Estante",
            fields=[
                (
                    "num_estante",
                    models.AutoField(
                        db_column="num_estante", primary_key=True, serialize=False
                    ),
                ),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                (
                    "dimensiones",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dimensiones",
                    ),
                ),
                (
                    "codigo_almacen",
                    models.ForeignKey(
                        db_column="codigo_almacen",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="estantes",
                        to="almacenamiento.almacen",
                        verbose_name="Almacén",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estante",
                "verbose_name_plural": "Estantes",
                "db_table": "estante",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Existencia",
            fields=[
                (
                    "codigo_existencias",
                    models.AutoField(
                        db_column="codigo_existencias",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "num_estante",
                    models.ForeignKey(
                        db_column="num_estante",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="existencias",
                        to="almacenamiento.estante",
                        verbose_name="Estante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Existencia",
                "verbose_name_plural": "Existencias",
                "db_table": "existencia",
                "ordering": ["-codigo_existencias"],
            },
        ),
    ]
