# Generated by Django 6.0.4 on 2026-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "documento",
                    models.CharField(
                        db_column="documento",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Número de Documento",
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=50, verbose_name="Primer Nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Segundo Nombre",
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=50, verbose_name="Primer Apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Segundo Apellido",
                    ),
                ),
                (
                    "correo_personal",
                    models.CharField(
                        blank=True,
                        db_column="correo_personal",
                        max_length=100,
                        null=True,
                        verbose_name="Correo Personal",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("PP", "Pasaporte"),
                            ("TI", "Tarjeta de Identidad"),
                        ],
                        default="CC",
                        max_length=30,
                        null=True,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "programa",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Programa"
                    ),
                ),
                (
                    "ficha",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ficha"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Contraseña"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Usuario", "Usuario"),
                            ("Administrador", "Administrador"),
                        ],
                        default="Usuario",
                        max_length=50,
                        null=True,
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuario",
            },
        ),
    ]
