# Generated by Django 6.0.4 on 2026-07-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Usuario', 'Usuario'), ('Administrador', 'Administrador')], default='Usuario', max_length=20)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('numero_ficha', models.CharField(blank=True, default='', max_length=20, verbose_name='Número de ficha')),
                ('nombre_programa', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del programa')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2, verbose_name='Tipo de documento')),
                ('password', models.CharField(default='', max_length=255)),
                ('reset_token', models.CharField(blank=True, default='', max_length=40)),
                ('reset_token_expira', models.FloatField(default=0)),
                ('destinado', models.ForeignKey(blank=True, db_column='destinado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinados', to='usuario.usuario')),
                ('solicitado', models.ForeignKey(blank=True, db_column='solicitado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicita', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
