# Generated by Django 6.0.4 on 2026-08-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('documento', models.CharField(db_column='documento', default='', max_length=20, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(default='', max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(default='', max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('correo_personal', models.EmailField(db_column='correo_personal', default='', max_length=100, verbose_name='Correo Personal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=30, verbose_name='Tipo de documento')),
                ('programa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Programa')),
                ('ficha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ficha')),
                ('rol', models.CharField(choices=[('Usuario', 'Usuario'), ('Administrador', 'Administrador')], default='Usuario', max_length=20)),
                ('password', models.CharField(default='', max_length=255)),
                ('reset_token', models.CharField(blank=True, default='', max_length=40)),
                ('reset_token_expira', models.FloatField(default=0)),
                ('destinado', models.ForeignKey(blank=True, db_column='destinado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinados', to='usuario.usuario')),
                ('solicitado', models.ForeignKey(blank=True, db_column='solicitado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicita', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
