# Generated by Django 6.0.4 on 2026-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Usuario', 'Usuario'), ('Administrador', 'Administrador')], default='Usuario', max_length=50, null=True, verbose_name='Rol'),
        ),
    ]
