# Generated by Django 6.0.4 on 2026-07-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, verbose_name='Documento / ID del usuario')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del responsable')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_solicitud', models.TextField(blank=True, default='', verbose_name='Motivo de la solicitud')),
                ('motivo_rechazo', models.TextField(blank=True, default='', verbose_name='Motivo de rechazo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('activo', 'Activo'), ('parcial', 'Devuelto parcialmente'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de préstamo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, help_text='Fecha límite para la devolución. Dejar vacío si no aplica.', null=True, verbose_name='Fecha de vencimiento')),
                ('hora_max_entrega', models.TimeField(blank=True, help_text='Hora límite del día en que debe devolverse el préstamo.', null=True, verbose_name='Hora máxima de entrega')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='ItemPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad prestada')),
                ('serial_entregado', models.CharField(blank=True, default='', help_text='Número de serie de la herramienta física entregada al usuario.', max_length=200, verbose_name='Serial / N° de serie entregado')),
                ('devuelto', models.BooleanField(db_index=True, default=False, verbose_name='Devuelto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_prestamo', to='inventario.producto', verbose_name='Producto')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prestamo.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Ítem de préstamo',
                'verbose_name_plural': 'Ítems de préstamo',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='itemprestamo_cantidad_gte_1')],
            },
        ),
    ]
