# Generated by Django 6.0.4 on 2026-08-14 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "codigo_prestamo",
                    models.AutoField(
                        db_column="codigo_prestamo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de préstamo",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        db_column="documento",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="prestamos",
                        to="usuario.usuario",
                        verbose_name="Usuario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "db_table": "prestamo",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetallePrestamo",
            fields=[
                (
                    "numero_detalle",
                    models.AutoField(
                        db_column="numero_detalle", primary_key=True, serialize=False
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("cantidad", models.IntegerField(default=1, verbose_name="Cantidad")),
                (
                    "codigo_herramienta",
                    models.ForeignKey(
                        db_column="codigo_herramienta",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="detalles_prestamo",
                        to="inventario.herramienta",
                        verbose_name="Herramienta",
                    ),
                ),
                (
                    "codigo_prestamo",
                    models.ForeignKey(
                        db_column="codigo_prestamo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prestamo.prestamo",
                        verbose_name="Préstamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de préstamo",
                "verbose_name_plural": "Detalles de préstamo",
                "db_table": "detalle_prestamo",
            },
        ),
    ]
