# Generated by Django 6.0.4 on 2026-08-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo_prestamo', models.AutoField(db_column='codigo_prestamo', primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('activo', 'Activo'), ('parcial', 'Devuelto parcialmente'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=50, verbose_name='Estado')),
                ('num_herramienta', models.IntegerField(blank=True, null=True, verbose_name='Número de herramienta')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del responsable')),
                ('motivo_solicitud', models.TextField(blank=True, default='', verbose_name='Motivo de la solicitud')),
                ('motivo_rechazo', models.TextField(blank=True, default='', verbose_name='Motivo de rechazo')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de préstamo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de vencimiento')),
                ('hora_max_entrega', models.TimeField(blank=True, null=True, verbose_name='Hora máxima de entrega')),
                ('documento', models.ForeignKey(blank=True, db_column='documento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='usuario.usuario', verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'prestamo',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('numero_detalle', models.AutoField(db_column='numero_detalle', primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad prestada')),
                ('serial_entregado', models.CharField(blank=True, default='', max_length=200, verbose_name='Serial entregado')),
                ('devuelto', models.BooleanField(db_index=True, default=False, verbose_name='Devuelto')),
                ('codigo_herramienta', models.ForeignKey(blank=True, db_column='codigo_herramienta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_prestamo', to='inventario.producto', verbose_name='Herramienta / Producto')),
                ('codigo_prestamo', models.ForeignKey(blank=True, db_column='codigo_prestamo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prestamo.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Detalle de préstamo',
                'verbose_name_plural': 'Detalles de préstamo',
                'db_table': 'detalle_prestamo',
            },
        ),
    ]
