# Generated by Django 6.0.4 on 2026-07-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('inventario', 'Inventario'), ('prestamos', 'Préstamos'), ('devoluciones', 'Devoluciones'), ('mantenimiento', 'Mantenimiento'), ('almacenamiento', 'Almacenamiento'), ('usuarios', 'Usuarios')], max_length=30, verbose_name='Módulo')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='Formato')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre de archivo')),
                ('generado_por', models.CharField(default='Sistema', max_length=150, verbose_name='Generado por')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('total_registros', models.PositiveIntegerField(default=0, verbose_name='Total de registros')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
