# Generated by Django 6.0.4 on 2026-08-14 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MantenimientoCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "num_mantenimiento",
                    models.AutoField(
                        db_column="num_mantenimiento", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo_mantenimiento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de mantenimiento",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de ingreso",
                    ),
                ),
                (
                    "fecha_salida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de salida"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "codigo_herramienta",
                    models.ForeignKey(
                        db_column="codigo_herramienta",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="mantenimientos",
                        to="inventario.herramienta",
                        verbose_name="Herramienta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
                "db_table": "mantenimiento",
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.CreateModel(
            name="DetalleMantenimiento",
            fields=[
                (
                    "detalle_mantenimiento",
                    models.AutoField(
                        db_column="detalle_mantenimiento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accion_realizada",
                    models.TextField(
                        blank=True, null=True, verbose_name="Acción realizada"
                    ),
                ),
                (
                    "materiales_usados",
                    models.TextField(
                        blank=True, null=True, verbose_name="Materiales usados"
                    ),
                ),
                (
                    "fecha_mantenimiento",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de mantenimiento",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "num_mantenimiento",
                    models.ForeignKey(
                        db_column="num_mantenimiento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="mantenimiento.mantenimiento",
                        verbose_name="Mantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Mantenimiento",
                "verbose_name_plural": "Detalles de Mantenimiento",
                "db_table": "detalle_mantenimiento",
                "ordering": ["-fecha_mantenimiento"],
            },
        ),
        migrations.CreateModel(
            name="BitacoraEstado",
            fields=[
                (
                    "codigo_bitacora",
                    models.AutoField(
                        db_column="codigo_bitacora", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "nivel_estado",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nivel de estado",
                    ),
                ),
                (
                    "num_mantenimiento",
                    models.ForeignKey(
                        db_column="num_mantenimiento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacoras_estado",
                        to="mantenimiento.mantenimiento",
                        verbose_name="Mantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora de Estado",
                "verbose_name_plural": "Bitácoras de Estado",
                "db_table": "bitacora_estado",
            },
        ),
    ]
