# Generated by Django 6.0.4 on 2026-06-19 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_registro', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='abierto', max_length=20, verbose_name='Estado del registro')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad / urgencia')),
                ('fecha_reporte', models.DateField(verbose_name='Fecha de reporte / detección')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio mantenimiento')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha entrega real')),
                ('tiempo_empleado_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tiempo empleado (horas)')),
                ('descripcion_problema', models.TextField(verbose_name='Descripción del problema / falla')),
                ('acciones_realizadas', models.TextField(blank=True, null=True, verbose_name='Acciones realizadas / planificadas')),
                ('materiales_usados', models.TextField(blank=True, null=True, verbose_name='Materiales / repuestos usados')),
                ('notas_adicionales', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('evidencia_adicional', models.FileField(blank=True, null=True, upload_to='mantenimiento/evidencias/', verbose_name='Evidencia adjunta')),
                ('ubicacion_snapshot', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación al momento del registro')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo estimado')),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo real')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Última edición por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='inventario.producto', verbose_name='Ítem / Herramienta')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Técnico')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_edicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
                ('motivo_edicion', models.CharField(choices=[('correccion_error', 'Corrección de error'), ('actualizacion_imprevisto', 'Actualización por imprevisto'), ('adicion_evidencia', 'Adición de evidencia'), ('ajuste_estado', 'Ajuste de estado'), ('otro', 'Otro')], max_length=40, verbose_name='Motivo de edición')),
                ('detalle_motivo', models.CharField(blank=True, max_length=255, verbose_name='Detalle del motivo')),
                ('cambios', models.JSONField(default=dict, verbose_name='Campos modificados')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_mantenimiento', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_auditoria', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Cambio de mantenimiento',
                'verbose_name_plural': 'Cambios de mantenimiento',
                'ordering': ['-fecha_edicion'],
            },
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del estado')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código abreviado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción breve')),
                ('categoria', models.CharField(choices=[('danado', 'Dañado'), ('reparacion', 'En reparación'), ('obsoleto', 'Obsoleto'), ('calibracion', 'Calibración pendiente'), ('preventivo', 'Mantenimiento preventivo'), ('otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('impacto_disponibilidad', models.CharField(choices=[('no_disponible', 'No disponible'), ('parcialmente_disponible', 'Parcialmente disponible'), ('disponible_restringido', 'Disponible con restricción')], default='no_disponible', max_length=40, verbose_name='Impacto en disponibilidad')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Color asociado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tipo de Estado',
                'verbose_name_plural': 'Tipos de Estado',
                'db_table': 'mantenimiento_tipoestado',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='mantenimiento.tipoestado', verbose_name='Tipo de estado actual'),
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color (hex)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantenimiento_creados', to='usuario.usuario', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'db_table': 'mantenimiento_tipomantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='mantenimiento.tipomantenimiento', verbose_name='Tipo de mantenimiento'),
        ),
    ]
