# Generated by Django 6.0.4 on 2026-08-14 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_reporte'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin real / entrega'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del mantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_reporte',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte / detección'),
        ),
    ]
