# Generated by Django 6.0.4 on 2026-07-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='acciones_realizadas',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion_problema',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='evidencia_adicional',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='materiales_usados',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='notas_adicionales',
        ),
        migrations.AddField(
            model_name='tipoestado',
            name='nivel_estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Grave'), (4, 'Crítico')], default=1, verbose_name='Nivel de severidad'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_actualizados', to='usuario.usuario', verbose_name='Última edición por'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to='usuario.usuario', verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_responsable', to='usuario.usuario', verbose_name='Responsable / Técnico'),
        ),
        migrations.AlterField(
            model_name='mantenimientocambio',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_mantenimiento', to='usuario.usuario', verbose_name='Editado por'),
        ),
        migrations.AlterField(
            model_name='tipoestado',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario', verbose_name='Creado por'),
        ),
        migrations.AlterModelTable(
            name='mantenimiento',
            table='mantenimiento_bitacoramantenimiento',
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('accion', 'Acción realizada'), ('repuesto', 'Repuesto / material usado'), ('nota', 'Nota adicional'), ('cierre', 'Cierre / entrega')], max_length=20, verbose_name='Tipo de entrada')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('evidencia_adicional', models.FileField(blank=True, null=True, upload_to='mantenimiento/evidencias/', verbose_name='Evidencia adjunta')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del evento')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_mantenimiento_creados', to='usuario.usuario', verbose_name='Registrado por')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_mantenimiento', to='mantenimiento.tipomantenimiento', verbose_name='Tipo de mantenimiento (detalle)')),
            ],
            options={
                'verbose_name': 'Detalle de Mantenimiento',
                'verbose_name_plural': 'Detalles de Mantenimiento',
                'db_table': 'mantenimiento_detallemantenimiento',
                'ordering': ['creado_en'],
            },
        ),
    ]
