# Generated by Django 6.0.4 on 2026-08-18 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_fin_real',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_reporte',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
    ]
