import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from django.db import connection

with connection.cursor() as cursor:
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS inventario_movimientokardex (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tipo_movimiento varchar(20) NOT NULL,
            cantidad integer NOT NULL CHECK (cantidad >= 0),
            stock_anterior integer NOT NULL CHECK (stock_anterior >= 0),
            stock_nuevo integer NOT NULL CHECK (stock_nuevo >= 0),
            usuario_nombre varchar(150) NOT NULL,
            observaciones text NOT NULL,
            creado_en timestamp with time zone NOT NULL,
            producto_id bigint NOT NULL REFERENCES inventario_producto(id) ON DELETE CASCADE
        );
    """)
    print("Tabla inventario_movimientokardex creada/verificada en Neon Tech.")
