# Generated by Django 6.0.4 on 2026-08-14 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prestamo", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevolucionHerramienta",
            fields=[
                (
                    "codigo_devolucion",
                    models.AutoField(
                        db_column="codigo_devolucion", primary_key=True, serialize=False
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de devolución",
                    ),
                ),
                (
                    "codigo_prestamo",
                    models.ForeignKey(
                        db_column="codigo_prestamo",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="devoluciones",
                        to="prestamo.prestamo",
                        verbose_name="Préstamo",
                    ),
                ),
                (
                    "codigo_recibe",
                    models.ForeignKey(
                        db_column="codigo_recibe",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="devoluciones_recibidas",
                        to="usuario.usuario",
                        verbose_name="Usuario que recibe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolución de Herramienta",
                "verbose_name_plural": "Devoluciones de Herramientas",
                "db_table": "devolucion_herramientas",
                "ordering": ["-fecha"],
            },
        ),
    ]
