# Generated by Django 6.0.4 on 2026-07-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={},
        ),
    ]
