# Generated by Django 6.0.4 on 2026-07-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Devolución', 'verbose_name_plural': 'Devoluciones'},
        ),
    ]
